set(_CATKIN_CURRENT_PACKAGE "husky_custom_navigation")
set(husky_custom_navigation_VERSION "0.0.0")
set(husky_custom_navigation_MAINTAINER "administrator <administrator@todo.todo>")
set(husky_custom_navigation_PACKAGE_FORMAT "2")
set(husky_custom_navigation_BUILD_DEPENDS )
set(husky_custom_navigation_BUILD_EXPORT_DEPENDS )
set(husky_custom_navigation_BUILDTOOL_DEPENDS "catkin")
set(husky_custom_navigation_BUILDTOOL_EXPORT_DEPENDS )
set(husky_custom_navigation_EXEC_DEPENDS )
set(husky_custom_navigation_RUN_DEPENDS )
set(husky_custom_navigation_TEST_DEPENDS )
set(husky_custom_navigation_DOC_DEPENDS )
set(husky_custom_navigation_URL_WEBSITE "")
set(husky_custom_navigation_URL_BUGTRACKER "")
set(husky_custom_navigation_URL_REPOSITORY "")
set(husky_custom_navigation_DEPRECATED "")