# CMake generated Testfile for 
# Source directory: /home/fran/catkin_ws/src/husky/husky_gazebo
# Build directory: /home/fran/catkin_ws/build_isolated/husky_gazebo
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_husky_gazebo_roslaunch-check_launch_empty_world.launch "/home/fran/catkin_ws/build_isolated/husky_gazebo/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/fran/catkin_ws/build_isolated/husky_gazebo/test_results/husky_gazebo/roslaunch-check_launch_empty_world.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/fran/catkin_ws/build_isolated/husky_gazebo/test_results/husky_gazebo" "/opt/ros/noetic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/home/fran/catkin_ws/build_isolated/husky_gazebo/test_results/husky_gazebo/roslaunch-check_launch_empty_world.launch.xml\" \"/home/fran/catkin_ws/src/husky/husky_gazebo/launch/empty_world.launch\" ")
set_tests_properties(_ctest_husky_gazebo_roslaunch-check_launch_empty_world.launch PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/roslaunch/cmake/roslaunch-extras.cmake;66;catkin_run_tests_target;/home/fran/catkin_ws/src/husky/husky_gazebo/CMakeLists.txt;20;roslaunch_add_file_check;/home/fran/catkin_ws/src/husky/husky_gazebo/CMakeLists.txt;0;")
add_test(_ctest_husky_gazebo_roslaunch-check_launch_husky_playpen.launch "/home/fran/catkin_ws/build_isolated/husky_gazebo/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/fran/catkin_ws/build_isolated/husky_gazebo/test_results/husky_gazebo/roslaunch-check_launch_husky_playpen.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/fran/catkin_ws/build_isolated/husky_gazebo/test_results/husky_gazebo" "/opt/ros/noetic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/home/fran/catkin_ws/build_isolated/husky_gazebo/test_results/husky_gazebo/roslaunch-check_launch_husky_playpen.launch.xml\" \"/home/fran/catkin_ws/src/husky/husky_gazebo/launch/husky_playpen.launch\" ")
set_tests_properties(_ctest_husky_gazebo_roslaunch-check_launch_husky_playpen.launch PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/roslaunch/cmake/roslaunch-extras.cmake;66;catkin_run_tests_target;/home/fran/catkin_ws/src/husky/husky_gazebo/CMakeLists.txt;21;roslaunch_add_file_check;/home/fran/catkin_ws/src/husky/husky_gazebo/CMakeLists.txt;0;")
add_test(_ctest_husky_gazebo_roslaunch-check_launch_playpen.launch "/home/fran/catkin_ws/build_isolated/husky_gazebo/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/fran/catkin_ws/build_isolated/husky_gazebo/test_results/husky_gazebo/roslaunch-check_launch_playpen.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/fran/catkin_ws/build_isolated/husky_gazebo/test_results/husky_gazebo" "/opt/ros/noetic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/home/fran/catkin_ws/build_isolated/husky_gazebo/test_results/husky_gazebo/roslaunch-check_launch_playpen.launch.xml\" \"/home/fran/catkin_ws/src/husky/husky_gazebo/launch/playpen.launch\" ")
set_tests_properties(_ctest_husky_gazebo_roslaunch-check_launch_playpen.launch PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/roslaunch/cmake/roslaunch-extras.cmake;66;catkin_run_tests_target;/home/fran/catkin_ws/src/husky/husky_gazebo/CMakeLists.txt;22;roslaunch_add_file_check;/home/fran/catkin_ws/src/husky/husky_gazebo/CMakeLists.txt;0;")
add_test(_ctest_husky_gazebo_roslaunch-check_launch_realsense.launch "/home/fran/catkin_ws/build_isolated/husky_gazebo/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/fran/catkin_ws/build_isolated/husky_gazebo/test_results/husky_gazebo/roslaunch-check_launch_realsense.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/fran/catkin_ws/build_isolated/husky_gazebo/test_results/husky_gazebo" "/opt/ros/noetic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/home/fran/catkin_ws/build_isolated/husky_gazebo/test_results/husky_gazebo/roslaunch-check_launch_realsense.launch.xml\" \"/home/fran/catkin_ws/src/husky/husky_gazebo/launch/realsense.launch\" ")
set_tests_properties(_ctest_husky_gazebo_roslaunch-check_launch_realsense.launch PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/roslaunch/cmake/roslaunch-extras.cmake;66;catkin_run_tests_target;/home/fran/catkin_ws/src/husky/husky_gazebo/CMakeLists.txt;23;roslaunch_add_file_check;/home/fran/catkin_ws/src/husky/husky_gazebo/CMakeLists.txt;0;")
add_test(_ctest_husky_gazebo_roslaunch-check_launch_spawn_husky.launch "/home/fran/catkin_ws/build_isolated/husky_gazebo/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/fran/catkin_ws/build_isolated/husky_gazebo/test_results/husky_gazebo/roslaunch-check_launch_spawn_husky.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/fran/catkin_ws/build_isolated/husky_gazebo/test_results/husky_gazebo" "/opt/ros/noetic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/home/fran/catkin_ws/build_isolated/husky_gazebo/test_results/husky_gazebo/roslaunch-check_launch_spawn_husky.launch.xml\" \"/home/fran/catkin_ws/src/husky/husky_gazebo/launch/spawn_husky.launch\" ")
set_tests_properties(_ctest_husky_gazebo_roslaunch-check_launch_spawn_husky.launch PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/roslaunch/cmake/roslaunch-extras.cmake;66;catkin_run_tests_target;/home/fran/catkin_ws/src/husky/husky_gazebo/CMakeLists.txt;24;roslaunch_add_file_check;/home/fran/catkin_ws/src/husky/husky_gazebo/CMakeLists.txt;0;")
subdirs("gtest")
